# Generated by Django 4.2.6 on 2024-02-09 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_billingdetails_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='first_name',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='last_name',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
