# Generated by Django 4.2.6 on 2024-02-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_billingdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('parcel', 'Parcel'), ('on the way', 'On the way'), ('delivered', 'Delivered')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='postcode_zip',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='town_city',
            field=models.CharField(max_length=10),
        ),
    ]
