# Generated by Django 4.2.6 on 2024-02-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_orders_options_orders_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('proccesing', 'Proccesing'), ('parcel', 'Parceled'), ('on the way', 'On the way'), ('delivered', 'Delivered')], default='proccesing', max_length=20),
        ),
    ]
