# Generated by Django 4.2.6 on 2024-02-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_orders_product_orders_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='email',
        ),
    ]
