# Generated by Django 5.0 on 2024-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_billingdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('proccesing', 'Proccesing'), ('parcel', 'Parceled'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('cancaled', 'Cancaled')], default='proccesing', max_length=20),
        ),
    ]
