# Generated by Django 4.2.6 on 2024-01-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonor',
        ),
    ]
